import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './_sections/Navbar/Navbar';
import { BebasNeue } from './fonts';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Pascal is coding - Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${BebasNeue.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
